app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_index:
    path: /
    defaults: { _controller: AppBundle:Home:index }

default_admin:
    path: /admin
    defaults: { _controller: AppBundle:Default:admin }

#register_index:
#    path: /register/index
#    defaults: { _controller: AppBundle:Register:index }

user_success:
    path: /user/success
    defaults: { _controller: AppBundle:User:index }

user_edit:
    path: /user/edit
    defaults: { _controller: AppBundle:User:editUserData }

user_registration:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

activeuser_checktoken:
    path: /register/activate={token}
    #path: /register/activate
    defaults: { _controller: AppBundle:ActivateUser:checkToken }
    requirements:
       #token: '/^[0-9A-F]{40}$/i'
    methods: GET

personal_index:
    path: /personal/index
    defaults: { _controller: AppBundle:Personal:index }

post_new_index:
    path: /post/new
    defaults: { _controller: AppBundle:PostController\NewPost:index }

post_edit_index:
    path: /post/edit/{id}
    defaults: { _controller: AppBundle:PostController\EditPost:index }
    requirements:
        id: '\d+'

post_view_index:
    path: /post/view/{id}
    defaults: { _controller: AppBundle:PostController\ViewPost:index }
    requirements:
        id: '\d+'

post_delete_index:
    path: /post/delete/{id}
    defaults: { _controller: AppBundle:PostController\DeletePost:index }
    requirements:
        id: '\d+'

logout:
    path: /logout

admin_panel:
    path: /admin/panel/{id}
    defaults: { _controller: AppBundle:AdminPanel:index }
    requirements:
            id: '\d+'